apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tomronen/Platform-App.git'
    targetRevision: HEAD
    path: charts/platform-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: platform-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
